# Generated by Django 5.1.6 on 2025-02-12 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Deck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("ポケモン", "ポケモン"),
                            ("グッズ", "グッズ"),
                            ("サポート", "サポート"),
                            ("ポケモンのどうぐ", "ポケモンのどうぐ"),
                            ("スタジアム", "スタジアム"),
                            ("エネルギー", "エネルギー"),
                        ],
                        max_length=20,
                    ),
                ),
                ("count", models.IntegerField(default=1)),
                (
                    "deck",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cards",
                        to="deck.deck",
                    ),
                ),
            ],
        ),
    ]
