# Generated by Django 5.1.6 on 2025-02-14 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deck", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="is_key_card",
            field=models.BooleanField(default=False),
        ),
    ]
