# Generated by Django 5.1.6 on 2025-02-14 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deck", "0002_card_is_key_card"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="key_card_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
