# Generated by Django 5.1.6 on 2025-02-14 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deck", "0003_card_key_card_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="count",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
