# Generated by Django 5.1.6 on 2025-02-15 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deck", "0004_alter_card_count"),
    ]

    operations = [
        migrations.CreateModel(
            name="MulliganResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_trials", models.IntegerField(default=0)),
                ("total_mulligans", models.IntegerField(default=0)),
                ("mulligan_rate", models.FloatField(default=0.0)),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "deck",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="deck.deck"
                    ),
                ),
            ],
        ),
    ]
